services:
  caddy:
    image: caddy
    restart: always
    env_file: .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
    networks:
      - gateway
  auth-service:
    container_name: auth-service
    image: melowetty/fsp-auth-service
    depends_on:
      - auth-service-db
    restart: always
    env_file: 
      - auth-service.env
    expose:
      - 8081
    networks:
      - auth-service
      - user-service
      - gateway
  auth-service-db:
    image: postgres
    restart: always
    env_file: 
      - auth-service.env
    expose:
      - 5432
    volumes:
      - auth-service-db:/var/lib/postgresql/data
    networks:
      - auth-service
  user-service:
    container_name: user-service
    image: melowetty/fsp-user-service
    depends_on:
      - user-service-db
    restart: always
    env_file: 
      - user-service.env
    expose:
      - 8080
    networks:
      - user-service
      - gateway
  user-service-db:
    image: postgres
    restart: always
    env_file: 
      - user-service.env
    expose:
      - 5432
    volumes:
      - user-service-db:/var/lib/postgresql/data
    networks:
      - user-service
volumes:
  auth-service-db:
  user-service-db:
networks:
  auth-service:
  user-service:
  gateway:
    